const fs = require('fs');
const {resolve} = require('path');
const {layerConfigurations,useRootTraitType} = require("./src/config");
const {layersSetup} = require("./src/lib/hashlips/hl-node");
const {readdir} = require('fs').promises;

if (!process.argv[2]) {
    console.log('Please provide a path to a directory')
    process.exit(1)
}

if (!process.argv[3]) {
    console.log('Please provide an output file name')
    process.exit(1)
}


;(async () => {
    const layersConfigLists = [];
    for (let layerConfiguration of layerConfigurations) {
        layersConfigLists.push(layersSetup(layerConfiguration.layersOrder, {relativePathsTo:process.argv[2]}));
    }

    const jsFile = `/** This file is generated by list_files.js. Do not edit it manually. */\n
export const fileList = ${JSON.stringify(layersConfigLists, null, 2)};`
    fs.writeFileSync(process.argv[3], jsFile);

    // await buildFileList(process.argv[2], process.argv[3])
})();
