/** This file is generated by list_files.js. Do not edit it manually. */

export const fileList = [
  [
    {
      "id": 0,
      "name": "Background",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": false,
          "weight": 5,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "coulds",
          "filename": "coulds#5.png",
          "path": "hashlips/layers/Background/coulds#5.png",
          "zindex": "",
          "trait": "Background",
          "traitValue": "coulds"
        },
        {
          "sublayer": false,
          "weight": 5,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "stars",
          "filename": "stars#5.png",
          "path": "hashlips/layers/Background/stars#5.png",
          "zindex": "",
          "trait": "Background",
          "traitValue": "stars"
        },
        {
          "sublayer": false,
          "weight": 5,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 2,
          "name": "swirl",
          "filename": "swirl#5.png",
          "path": "hashlips/layers/Background/swirl#5.png",
          "zindex": "",
          "trait": "Background",
          "traitValue": "swirl"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 1,
      "name": "Back Accessory",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": true,
          "weight": 50,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "Backpack",
          "filename": "Backpack#50",
          "path": "hashlips/layers/Back Accessory/Backpack#50",
          "zindex": "",
          "elements": [
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "1backpack-lines",
              "filename": "1backpack-lines.png",
              "path": "hashlips/layers/Back Accessory/Backpack#50/1backpack-lines.png",
              "zindex": "",
              "trait": "Back Accessory",
              "traitValue": "Backpack"
            },
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 1,
              "name": "backpack-FILL",
              "filename": "backpack-FILL.png",
              "path": "hashlips/layers/Back Accessory/Backpack#50/backpack-FILL.png",
              "zindex": "",
              "trait": "Back Accessory",
              "traitValue": "Backpack"
            }
          ],
          "trait": "layers",
          "traitValue": "Backpack"
        },
        {
          "sublayer": false,
          "weight": 40,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "rockets",
          "filename": "rockets#40.png",
          "path": "hashlips/layers/Back Accessory/rockets#40.png",
          "zindex": "",
          "trait": "Back Accessory",
          "traitValue": "rockets"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 2,
      "name": "Head",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": false,
          "weight": 3,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "faceA",
          "filename": "faceA#3.png",
          "path": "hashlips/layers/Head/faceA#3.png",
          "zindex": "",
          "trait": "Head",
          "traitValue": "faceA"
        },
        {
          "sublayer": false,
          "weight": 3,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "faceB",
          "filename": "faceB#3.png",
          "path": "hashlips/layers/Head/faceB#3.png",
          "zindex": "",
          "trait": "Head",
          "traitValue": "faceB"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 3,
      "name": "Clothes",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": true,
          "weight": 44,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "Shirt three",
          "filename": "Shirt three#44",
          "path": "hashlips/layers/Clothes/Shirt three#44",
          "zindex": "",
          "elements": [
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "3shadow",
              "filename": "3shadow.png",
              "path": "hashlips/layers/Clothes/Shirt three#44/3shadow.png",
              "zindex": "",
              "trait": "Clothes",
              "traitValue": "Shirt three"
            },
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 1,
              "name": "shirt-FILL",
              "filename": "shirt-FILL.png",
              "path": "hashlips/layers/Clothes/Shirt three#44/shirt-FILL.png",
              "zindex": "",
              "trait": "Clothes",
              "traitValue": "Shirt three"
            }
          ],
          "trait": "layers",
          "traitValue": "Shirt three"
        },
        {
          "sublayer": false,
          "weight": 30,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "floral",
          "filename": "floral#30.png",
          "path": "hashlips/layers/Clothes/floral#30.png",
          "zindex": "",
          "trait": "Clothes",
          "traitValue": "floral"
        },
        {
          "sublayer": false,
          "weight": 30,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 2,
          "name": "gray tee",
          "filename": "gray tee#30.png",
          "path": "hashlips/layers/Clothes/gray tee#30.png",
          "zindex": "",
          "trait": "Clothes",
          "traitValue": "gray tee"
        },
        {
          "sublayer": false,
          "weight": 3,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 3,
          "name": "shirt one ",
          "filename": "shirt one #3.png",
          "path": "hashlips/layers/Clothes/shirt one #3.png",
          "zindex": "",
          "trait": "Clothes",
          "traitValue": "shirt one "
        },
        {
          "sublayer": false,
          "weight": 3,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 4,
          "name": "shirt two",
          "filename": "shirt two#3.png",
          "path": "hashlips/layers/Clothes/shirt two#3.png",
          "zindex": "",
          "trait": "Clothes",
          "traitValue": "shirt two"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 4,
      "name": "Eyes",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": true,
          "weight": 50,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "eye",
          "filename": "z1,eye#50",
          "path": "hashlips/layers/Eyes/z1,eye#50",
          "zindex": "z1,",
          "elements": [
            {
              "sublayer": true,
              "weight": 50,
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "happy",
              "filename": "happy#50",
              "path": "hashlips/layers/Eyes/z1,eye#50/happy#50",
              "zindex": "z1,",
              "elements": [
                {
                  "sublayer": false,
                  "weight": "required",
                  "blendmode": "source-over",
                  "opacity": 1,
                  "id": 0,
                  "name": "eye2",
                  "filename": "eye2.png",
                  "path": "hashlips/layers/Eyes/z1,eye#50/happy#50/eye2.png",
                  "zindex": "z1,",
                  "trait": "Eyes",
                  "traitValue": "happy"
                }
              ],
              "trait": "Eyes",
              "traitValue": "happy"
            },
            {
              "sublayer": true,
              "weight": 50,
              "blendmode": "source-over",
              "opacity": 1,
              "id": 1,
              "name": "normal",
              "filename": "normal#50",
              "path": "hashlips/layers/Eyes/z1,eye#50/normal#50",
              "zindex": "z1,",
              "elements": [
                {
                  "sublayer": false,
                  "weight": "required",
                  "blendmode": "source-over",
                  "opacity": 1,
                  "id": 0,
                  "name": "eye1",
                  "filename": "eye1.png",
                  "path": "hashlips/layers/Eyes/z1,eye#50/normal#50/eye1.png",
                  "zindex": "z1,",
                  "trait": "Eyes",
                  "traitValue": "normal"
                }
              ],
              "trait": "Eyes",
              "traitValue": "normal"
            }
          ],
          "trait": "layers",
          "traitValue": "eye"
        },
        {
          "sublayer": false,
          "weight": 30,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "star eyes",
          "filename": "z1,star eyes#30.png",
          "path": "hashlips/layers/Eyes/z1,star eyes#30.png",
          "zindex": "z1,",
          "trait": "Eyes",
          "traitValue": "star eyes"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 5,
      "name": "Hair",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": true,
          "weight": 20,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "Hair",
          "filename": "z1,Hair#20",
          "path": "hashlips/layers/Hair/z1,Hair#20",
          "zindex": "z1,",
          "elements": [
            {
              "sublayer": false,
              "weight": 50,
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "bluehair",
              "filename": "bluehair#50.png",
              "path": "hashlips/layers/Hair/z1,Hair#20/bluehair#50.png",
              "zindex": "z1,",
              "trait": "Hair",
              "traitValue": "bluehair"
            },
            {
              "sublayer": false,
              "weight": 50,
              "blendmode": "source-over",
              "opacity": 1,
              "id": 1,
              "name": "purplehair",
              "filename": "purplehair#50.png",
              "path": "hashlips/layers/Hair/z1,Hair#20/purplehair#50.png",
              "zindex": "z1,",
              "trait": "Hair",
              "traitValue": "purplehair"
            }
          ],
          "trait": "layers",
          "traitValue": "Hair"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 6,
      "name": "Accessory",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": true,
          "weight": 10,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "Helmet",
          "filename": "Helmet#10",
          "path": "hashlips/layers/Accessory/Helmet#10",
          "zindex": "",
          "elements": [
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "Helmet",
              "filename": "Helmet.png",
              "path": "hashlips/layers/Accessory/Helmet#10/Helmet.png",
              "zindex": "",
              "trait": "Accessory",
              "traitValue": "Space Helmet"
            }
          ],
          "trait": "layers",
          "traitValue": "Space Helmet"
        },
        {
          "sublayer": false,
          "weight": 1,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "MetallicShades",
          "filename": "MetallicShades#1.png",
          "path": "hashlips/layers/Accessory/MetallicShades#1.png",
          "zindex": "",
          "trait": "Accessory",
          "traitValue": "MetallicShades"
        },
        {
          "sublayer": false,
          "weight": 100,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 2,
          "name": "NONE",
          "filename": "NONE#100.png",
          "path": "hashlips/layers/Accessory/NONE#100.png",
          "zindex": "",
          "trait": "Accessory",
          "traitValue": "NONE"
        },
        {
          "sublayer": true,
          "weight": 25,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 3,
          "name": "Purple Glasses",
          "filename": "Purple Glasses#25",
          "path": "hashlips/layers/Accessory/Purple Glasses#25",
          "zindex": "",
          "elements": [
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 0,
              "name": "Glasses front",
              "filename": "Glasses front.png",
              "path": "hashlips/layers/Accessory/Purple Glasses#25/Glasses front.png",
              "zindex": "",
              "trait": "Accessory",
              "traitValue": "Purple Glasses"
            },
            {
              "sublayer": false,
              "weight": "required",
              "blendmode": "source-over",
              "opacity": 1,
              "id": 1,
              "name": "Glasses back",
              "filename": "z-10,Glasses back.png",
              "path": "hashlips/layers/Accessory/Purple Glasses#25/z-10,Glasses back.png",
              "zindex": "z-10,",
              "trait": "Accessory",
              "traitValue": "Purple Glasses"
            }
          ],
          "trait": "layers",
          "traitValue": "Purple Glasses"
        }
      ],
      "bypassDNA": false
    },
    {
      "id": 7,
      "name": "Shirt Accessories",
      "blendmode": "source-over",
      "opacity": 1,
      "elements": [
        {
          "sublayer": false,
          "weight": 1,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 0,
          "name": "Golden Sakura",
          "filename": "Golden Sakura#1.png",
          "path": "hashlips/layers/Shirt Accessories/Golden Sakura#1.png",
          "zindex": "",
          "trait": "Shirt Accessories",
          "traitValue": "Golden Sakura"
        },
        {
          "sublayer": false,
          "weight": 40,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 1,
          "name": "gold chain",
          "filename": "gold chain#40.png",
          "path": "hashlips/layers/Shirt Accessories/gold chain#40.png",
          "zindex": "",
          "trait": "Shirt Accessories",
          "traitValue": "GOLDEN NECKLACE"
        },
        {
          "sublayer": false,
          "weight": 40,
          "blendmode": "source-over",
          "opacity": 1,
          "id": 2,
          "name": "nametag",
          "filename": "nametag#40.png",
          "path": "hashlips/layers/Shirt Accessories/nametag#40.png",
          "zindex": "",
          "trait": "Shirt Accessories",
          "traitValue": "nametag"
        }
      ],
      "bypassDNA": false
    }
  ]
];