/** This file is generated by list_files.js. Do not edit it manually. */

export const allLayers = {
  "Background": [
    "Black#1.png"
  ],
  "Bottom lid": [
    "High#20.png",
    "Low#40.png",
    "Middle#40.png"
  ],
  "Eye color": [
    "Cyan#1.png",
    "Green#1.png",
    "Pink#1.png",
    "Purple#1.png",
    "Red#1.png",
    "Yellow#10.png"
  ],
  "Eyeball": [
    "Red#50.png",
    "White#50.png"
  ],
  "Goo": [
    "Green#1.png"
  ],
  "Iris": [
    "Large#20.png",
    "Medium#20.png",
    "Small#60.png"
  ],
  "Shine": [
    "Shapes#100.png"
  ],
  "Top lid": [
    "High#30.png",
    "Low#20.png",
    "Middle#50.png"
  ]
}